### ISSUE TITLE
Add simplifications for elm/random

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#109]
```elm
Random.uniform a []
--> Random.constant a

Random.weighted ( weight, a ) []
--> Random.constant a

Random.weighted tuple []
--> Random.constant (Tuple.first tuple)

Random.list 0 generator
--> Random.constant []

Random.map identity generator
--> generator

Random.andThen Random.constant generator
--> generator
```

Also detect when `Random.lazy` is unnecessary?

**Comment by lue-bird** [comment]
Maybe also
```elm
Random.list 0 generator
--> Random.map List.singleton generator

Random.map (always a)
--> Random.constant a
```

**Comment by jfmengels** [comment]
I think I'm on board with
```elm
Random.list 1 generator
--> Random.map List.singleton generator
```
though I could imagine some people finding the former one more readable.

---

Should
```elm
Random.andThen f (Random.constant x)
--> f x
```
be
```elm
Random.andThen f (Random.constant x)
--> Random.constant (f x)
```
? If so this could be done but I could also imagine quickly getting ugly :thinking: 

But let's try it. And I'm on board with the rest :+1:

**Comment by lue-bird** [comment]
No, adding `constant` would be wrong.
Maybe you can make it work in your head if you look at the same simplification for `Maybe`: https://github.com/jfmengels/elm-review-simplify/blob/main/src/Simplify.elm#L372-L373
