### ISSUE TITLE
`case`-ing when `Maybe.withDefault` will do

### ISSUE THREAD

**Issue by SiriusStarr** [jfmengels/elm-review-simplify#139]
You would know better than I if there are appreciable performance benefits to the `case`, in which case this should probably be avoided, but I've encountered this pattern quite a bit  

```elm
case expression of
    Just x ->
        x

    Nothing ->
        y
```

which is easily replaceable by the more clear and concise `Maybe.withDefault y (expression)`

**Comment by lue-bird** [comment]
Feels more like a code-style change to me, similar to how elm-analyze reports `Nothing -> Nothing` cases.

On the performance side, the default value will in practice usually cheap to eagerly compute. But also some times not, especially with "else handle the rest" like in recursion.
```elm
firstJust : NonEmptyList (Maybe a) -> Maybe a
firstJust ( head, tail ) =
    case head of
        Just headContent -> headContent
        Nothing ->
            List.Extra.findMap identity tail
-->
firstJust : NonEmptyList (Maybe a) -> Maybe a
firstJust ( head, tail ) =
    head |> Maybe.withDefault (List.Extra.findMap identity tail)
```
(Also not sure I like this rule myself, even from a code understandability side.)

**Comment by SiriusStarr** [comment]
Ehhh, I forgot `Maybe.withDefault` isn't lazy.  Closing this, though I'd still like a solution to flag this for trivial cases.
