### ISSUE TITLE
Additional `List.intersperse` simplifications

### ISSUE THREAD

**Issue by lue-bird** [jfmengels/elm-review-simplify#142]
`List.intersperse a [] --> []` already exist. Possible additions:
```elm
List.intersperse a [ b ]
--> [ b ]
-- which includes for example
List.intersperse a << List.singleton
--> List.singleton

List.intersperse a [ b, c ]
--> [ b, a, c ]
```
I imagine the last one is controversial because you sometimes expect to add more elements to the list in the future or just want make the separators the rule, like
```elm
[ navigationPanelUi
, channelMessagesUi
]
    |> List.intersperse (Ui.spacer 10)
-->
[ navigationPanelUi
, Ui.spacer 10
, channelMessagesUi
]
```
Since we also don't for example fix `List.sum [ a, b ]` to `a + b` it probably makes sense to not add this check to `simplify` (but to something like [miniBill/elm-review-optimize](https://github.com/miniBill/elm-review-optimize))

**Comment by jfmengels** [comment]
I'm in favor of the former one, but as you suggested not in favor for the last one (where the element gets introduced) for the reasons you mentioned.
