### ISSUE TITLE
Add List.reverse [ a ] --> [ a ]

### ISSUE THREAD

**Issue by lue-bird** [jfmengels/elm-review-simplify#143]
`sort`, `sortBy`, `sortWith` already have a simple check for returning the list unchanged when it's a singleton list.

```elm
List.reverse [ a ]
--> [ a ]

-- not shown in summary
List.reverse (List.singleton a)
--> List.singleton a

-- not shown in summary
List.reverse << List.singleton
--> List.singleton
```

**Comment by jfmengels** [comment]
We can do the same for `String.reverse` when we see `String.reverse (String.fromChar c)`
