### ISSUE TITLE
Incorrect suggestion for `Set.size (Set.fromList [ x, y, z ])`

### ISSUE THREAD

**Issue by jiegillet** [jfmengels/elm-review-simplify#19]
Example code:

```elm
triangleKind x y z =
    case Set.size (Set.fromList [ x, y, z ]) of
        1 ->
            Equilateral
         2 ->
            Isosceles
        _ ->
            Scalene
```

The suggestion is

```
Simplify: The size of the set is 3

20|     triangleKind x y z =
21|         case Set.size (Set.fromList [ x, y, z ]) of
                 ^^^^^^^^
22|             1 ->

The size of the set can be determined by looking at the code.
```

The suggestion is incorrect since `[x, y, z]` could be a smaller set than size 3.

The check could be dropped, or refined to trigger only for lists of literal values and the size would be obtained from`Set.fromList >> Set.size`.

I'm happy to do a PR, please advise :)

**Comment by jfmengels** [comment]
Thanks for the report! I'd love a PR for either solution 🙂
Let me know if you need help or want me to do it.
