### ISSUE TITLE
elm-review-simplify should never remove elm/json

### ISSUE THREAD

**Issue by miniBill** [jfmengels/elm-review-simplify#238]
The Elm compiler gets really unhappy if elm/json is removed, and it's hard-ish to fix

**Comment by lue-bird** [comment]
Maybe you wanted to open this issue in https://github.com/jfmengels/elm-review-unused/tree/1.2.0?

**Comment by miniBill** [comment]
Should I reopen https://github.com/jfmengels/elm-review-unused/issues/30 or open a new issue?
