### ISSUE TITLE
Should Simplify change field access functions to field access syntax? 

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#24]
This is a proposal to be discussed. Should Simplify make the following change?

```elm
.field a
--> a.field
```

This change can be considered as a code style choice.

The former does have a bigger performance footprint than the latter:
```js
// .field a
function ($) { return $.field; }(a)
// a.field
a.field
```

though that's probably something that the Elm compiler and/or `elm-optimize-level-2` can help with (TODO create an issue for that :) )

My gut feeling right now is that it's worth making the change because `a.field` is both simpler and more performant. We would also have more consistent code.

## Pipelines

What about pipelines? If we do this in pipelines then we would end up with this result:

```elm
    input
        |> fn1
        |> .field
        |> fn2
    --> (after elm-format)
    (input
        |> fn1
    ).field
        |> fn2
```

but `a = input |> .field` on its own should probably be transformed to `input.field`?

**Comment by gampleman** [comment]
I'll just summarize a quick counterpoint from slack, which is that in composite expressions the reading order is better in prefix notation:

```elm
formatEmail (.body (collateReport (.customers (process order))))
```

vs

```elm
formatEmail (collateReport (process order).customers).body
```

In the second case your eyes have to dart left and right to figure out how information flows.

**Comment by jfmengels** [comment]
Thank you. Yeah, I think that closes the argument for now. Maybe it still makes sense for very simple ".foo value" but I'm still not sure. In most cases I'd like to see this version in my work codebase. I won't implement it for now at least, to reflect a bit more on it.

**Comment by lue-bird** [comment]
Should we close this since this is code style related, not complexity related?

**Comment by jfmengels** [comment]
Sure, let's close this.
