### ISSUE TITLE
Simplify List.singleton x to [ x ]

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#244]
This is a lot more idiomatic Elm code.
```elm
List.singleton x
--> [ x ]
```

I don't know if we should so in the case of pipelines
```elm
f
  |> g
  |> h
  |> List.singleton
-->
[ f
    |> g
    |> h
]
```
but I feel like it will end up bringing more clarity to the code maybe? I've had similar push-backy thoughts on other simplifications (`List.map f [ x ]` --> `[ f x ]`) but in the end the results did feel nicer, so I think we should do it.

What do you think?

**Comment by lue-bird** [comment]
IMO this is subjective and code style related, not removing complexity/simplifying.
```elm
document : Browser.Document
document =
    { ... body =
        some
            |> ui
            |> Element.layout []
            |> List.singleton
    }
```
In my mind, this exactly like the debate about `always` vs `\_ ->`: Something that is best configured in a separate rule if you have a particular preference.

I do not feel as strongly about the case where `List.singleton` is applied, not piped but fixing only that case will feel inconsistent and random, so I'd prefer not to add it
