### ISSUE TITLE
Basic operations on integer literals

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#259]
In the following examples I'm using `1` but imagine any literal integer (so `1` but not `1.0`)

- [ ] `toFloat 1` -> `1`
- [ ] `round 1` -> `1`
- [ ] `ceiling 1` -> `1`
- [ ] `floor 1` -> `1`
- [ ] `truncate 1` -> `1`

Compositions of these functions:
- [ ] `round << toFloat` -> `identity`
- [ ] `ceiling << toFloat` -> `identity`
- [ ] `floor << toFloat` -> `identity`
- [ ] `truncate << toFloat` -> `identity`

**Comment by jfmengels** [comment]
Should we also simplify `floor 1.2` to `1`? :thinking:

**Comment by lue-bird** [comment]
To add:
```elm
round (round n) -> round n
ceiling (ceiling n) -> ceiling n
floor (floor n) -> floor n
truncate (truncate n) -> truncate n
```
can be done using `operationDoesNotChangeResultOfOperationCheck` and `operationDoesNotChangeResultOfOperationCompositionCheck`

**Comment by jfmengels** [comment]
Those don't type check so we don't have to handle them.

**Comment by lue-bird** [comment]
True, those don't return `number`, my mistake
