### ISSUE TITLE
Split tests up

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#266]
The `SimplifyTest` file has just reached an impressive 30 000 lines of code. And my computer fan is the one telling me it's impressive, making it quite hard/slow to work with (even `elm-format` is really struggling to work with it reliably for me).

I've been thinking about splitting it up, roughly by the existing `describe`s we have in that file (so one file for `Dict`, one file for `Set`, etc.).

Does that sound like an okay plan to you, or would this be more of a pain than a help?

**Comment by lue-bird** [comment]
sounds goof to me
