### ISSUE TITLE
sort, then head is equivalent to minimum

### ISSUE THREAD

**Issue by lue-bird** [jfmengels/elm-review-simplify#296]
```elm
List.head (List.sort list)
--> List.minimum list
```
Sadly, no `minimumBy` and `minimumWith` exist.

(found in the [FSharpLint default config](https://github.com/fsprojects/FSharpLint/blob/0007ec1e83a1043d74bcd5a0067c6483657faa26/src/FSharpLint.Core/DefaultConfiguration.json#L290-L291))

**Comment by morteako** [comment]
I guess also
```elm
List.head (List.reverse (List.sort list))
--> List.maximum list
```

**Comment by jfmengels** [comment]
I didn't think I would see this one report anything in practce, but at work I found both the `List.minimum` and the `List.maximum` cases, so this is very nice 😊
