### ISSUE TITLE
String.length "abc" should not be simplified

### ISSUE THREAD

**Issue by MartinSStewart** [jfmengels/elm-review-simplify#3]
Using `String.length "abc"` is often deliberate. Writing 3 instead says nothing about where that number came from.

**Comment by jfmengels** [comment]
Can you give examples where this would be deliberate? I agree that the fix should not always be applied and that an often better solution is to extract this value to a variable (hence why there is a prompt to fix the issue).

I still think it's valuable to know that there is this code that could be simplified or improved in meaning through a variable name. But if you disagree, examples would help.

**Comment by MartinSStewart** [comment]
In my case, the actual code looks like this (it's related to insurance claims)
```elm
String.dropLeft (String.length "tooth_") tooth
```
The "tooth_" string is prefixed to some of our data so we have to remove it to get the actual value. But if we just did `String.dropLeft 6 tooth` it would be much less clear what is going on.

That said, "tooth_" does appear in one or two other places. I guess what we should do is write `toothPrefix = "tooth_"` and use that instead which would improve our code and prevent simplify from simplifying this case. So maybe this is a non-issue?

**Comment by jfmengels** [comment]
In this case I'd go for extracting this to a variable yeah. Or creating a function like
```elm
removePrefix prefix str =
  String.dropLeft (String.length prefix) str
```
which sounds like it could be used in different places in your case anyway.

> So maybe this is a non-issue?

With this example at least yeah. Let's see if other similar situations come up (in new issues though, otherwise we'll never close this issue).
