### ISSUE TITLE
New rule: NoUnreachableCode/NoUnreachableNestedCode

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#30]
**What the rule should do:**

The rule should detect unreachable branches. These unreachable branches contain dead code, and therefore logically unused code.

**What problems does it solve:**

Unreachable branches are an indicator of either:
- Error: errors in logical thinking, which the user should be made aware of
- Error: Usage of the wrong variable used instead of another of the same type
- work in progress that should be finished
- Simplification: code that could be simplified

**Example of things the rule would report:**

```elm
if (value == stringLiteral) then
  if (value != stringLiteral) then
    -- you can prove that this is dead code
  else
    -- nested else
else
  -- outer else
```

**Example of things the rule would not report:**

```elm
if (value == stringLiteral) then
  -- nested else
else
  -- outer else
```

**When (not) to enable this rule:**

???

**Questions:**

- Should this rule also warn about cases where the condition can be evaluated statically (like `if True then` or `if a == a then`), or should this be the task of another rule? (I'm leaning towards a different rule, but maybe in a different package.

- Do you see a more fitting name for the rule?

- Can you think of reasons not to have an automatic fix?

- Should the rule handle case expressions too?

```elm
case value of
  Foo ->
	case value of
		Foo ->
            1
        Bar ->
            2 -- dead branch, we know value == Foo
  Bar -> 2
```

I am wondering whether this will not be annoying in cases where you'll need to destructure again, but I think that's unwarranted concern :thinking: 

I think the first iteration of the rule can concentrate on handling if expressions only anyway.

**Comment by jfmengels** [comment]
I moved this from `elm-review-unused`. I think this package now covers more of the logic behind this.

What I'm slightly worried about is whether the rule will be able to add an automatic fix in all cases, because that's quite important for `Simplify`.

**Comment by lue-bird** [comment]
For `if`, this is already implemented, right? And https://github.com/jfmengels/elm-review-simplify/issues/229 covers the combination with `case..of`.
Should we close this?
