### ISSUE TITLE
Simplify pipelined accessor call into access

### ISSUE THREAD

**Issue by Janiczek** [jfmengels/elm-review-simplify#312]
**What the rule should do:**
Replace things like `foo |> .x` with `foo.x`, except for when the foo is a function call or operator call (eg. a pipeline).

**What problems does it solve:**
Makes things simpler?

**Example of things the rule would report:**

```elm
foo |> .x
--> foo.x
```

```elm
1 |> .x
--> 1.x, wouldn't typecheck but is valid syntax
```

```elm
{ x = 3 } |> .x
--> { x = 3 }.x, to be picked up by another rule later and simplify to 3
```

**Example of things the rule would not report:**

```elm
foo 1 |> .x
```

```elm
foo |> fn |> .x
```

**Should this be part of the Simplify rule or should it be a new rule?**
Simplify

**I am looking for:**

- Someone to implement it for me

**Comment by Janiczek** [comment]
I guess it might be related to a rule where `.x foo` is rewritten into `foo.x`, which could be thought of as a simpler variant of the above.
If we had some `RuleAstPred -> RuleAstPred` combinator way of making rules that work on fn calls also work on pipelined fn calls, then that simpler rule + that combinator would give you the rule I'm proposing above.

**Comment by jfmengels** [comment]
Right. I feel like we often have this discussion and I *keep* trying to do this :sweat_smile: 
Yeah, use [SiriusStarr/elm-review-pipeline-styles](https://dark.elm.dmy.fr/packages/SiriusStarr/elm-review-pipeline-styles/latest/) instead, and if it doesn't support this, then open an issue there.

**Comment by Janiczek** [comment]
fair, thanks
