### ISSUE TITLE
Merge case expressions

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-simplify#315]
**What the rule should do:**

If we have nested case expressions and one in one of the branches the only thing we do is pattern match again on the matched value, then we should combine the two case expressions into one.

**Example of things the rule would report:**

```elm
case maybeX of
  Just x ->
    case x of
      A -> 1
      B -> 2
      C -> 3
  Nothing ->
    y
-->
case maybeX of
  Just A -> 1
  Just B -> 2
  Just C -> 3
  Nothing ->
    y
```

To clarify, this would apply to any wrapper, not just for `Maybe`.

**Example of things the rule would not report:**

```elm
case maybeX of
  Just x ->
    let
      doingSomethingElse = 1
    in
    case x of
      A -> 1
      B -> 2
      C -> 3
```

I'm not sure yet, but maybe if there are more variables matched, then we may not want that repetition.

```elm
case maybeX of
  Something x otherThing ->
    case x of
      A -> 1
      B -> 2
      C -> 3
  SomethingElse ->
    y
```

**Should this be part of the Simplify rule or should it be a new rule?**

**Comment by lydell** [comment]
I do this sometimes, sometimes not. More not lately, I think. I also think it should be a separate rule.

A downside with it is that you can’t use “Add missing patterns” in intellij-elm as much, since it’s not smart enough to handle nested patterns.

**Comment by jfmengels** [comment]
Thank you for the input. I'll close this now as I agree it's probably not a great idea after all (at least for it to be enforced).

**Comment by jfmengels** [comment]
Oh, here's probably the best reason NOT to do this: It changes how the compiler will respond if a new variant is added.

If we have `type X = A | B` and we want to add a variant `C`:

```elm
case maybeX of
  Just x ->
    case x of
      A -> 1
      B -> 2
      -- The compiler will remind us about an unhandled case
  _ -> 3
```
If it's flattened, it won't necessarily do so, depending on the rest of the branches:
```elm
case maybeX of
  Just A -> 1
  Just B -> 2
  _ -> 3
  -- No compiler reminder :'(
```
