### ISSUE TITLE
Add type path to unneccesary case error

### ISSUE THREAD

**Issue by stefan-wullems** [jfmengels/elm-review-simplify#36]
## Pain point

When adding `elm-review-simplify` to a project that is reasonably mature already, it seems very likely to run into `Unneccesary case expression` errors:

```
(fix) Simplify: Unnecessary case expression

128| viewCheckoutError findOfferError =
129|     case findOfferError of
         ^^^^
130|         Offer.NotInValidityPeriodError _ _ ->

All the branches of this case expression resolve to the same value. You can
remove the case expression and replace it with the body of one of the branches.
```

If I don't want to tackle these right now, I might reference these types in an `Simplify.ignoreCaseOfForTypes` call.

Right now I have to manually go into the codebase and track down the module path leading to this type which is a bit tedious.

## possible solution

I think it would be convenient if the rule already did this work for me by adding to the error message:

```
(fix) Simplify: Unnecessary case expression

128| viewCheckoutError findOfferError =
129|     case findOfferError of
         ^^^^
130|         Offer.NotInValidityPeriodError _ _ ->

All the branches of this case expression resolve to the same value. You can
remove the case expression and replace it with the body of one of the branches.

If this was intentional you can surpress this warning 
by adding `Path.To.Type` to the rule configuration through `Simplify.ignoreCaseOfForTypes`. 

I personally don't recommend to use this function too much, 
because this could be a sign of premature abstraction, 
and because I think that often [You Aren't Gonna Need this code](https://jfmengels.net/safe-dead-code-removal/#yagni-you-arent-gonna-need-it).
```

**Comment by jfmengels** [comment]
Hey @stefan-wullems 👋

Yeah, I was thinking of maybe removing this simplification. I can see how it prevents the compiler from helping you out in the future. I am still on the fence on whether to remove it altogether, or only for custom types specific to this project, and keep the simplification if all the referenced custom types come from dependencies.

I know that at least @janiczek put reservations on this simplification back when I added it (I would love your opinion again).

Otherwise, I agree that improving the error message would be nice 👍 

> If I don't want to tackle these right now

If you want to postpone, you can also use `elm-review suppress` (https://jfmengels.net/stop-the-bleed/). Not to be abused, but it can be very useful.

**Comment by Janiczek** [comment]
I agree that having the full qualified type name in the error would be a nice usability improvement!

@jfmengels After months of usage, this specific check is the only thing in `Simplify` that I need to go change in `ReviewConfig`. It comes up reasonably often. I understand that sometimes it will give me warnings I actually care about! It's just that I mostly get the kind-of-false positives.

Here's how it looks currently:
```elm
    , Simplify.defaults
        |> Simplify.ignoreCaseOfForTypes
            -- These custom types only have one constructor, but we still want
            -- to pattern-match as we may add more in the future.
            [ "API.Endpoints.ActivationMetrics.ActivationMetricsEndpoint"
            , "API.Endpoints.CohortSize.CohortSizeEndpoint"
            , "Publisher.Activations.Integrations.Empty.Action"
            , "Publisher.Settings.Integrations.WebhooksConfig.Action"
            , "Publisher.ContextualCohorts.Builder.Predicate.PredicateModel"
            , "Publisher.ContextualCohorts.Builder.AST.AffinityType"
            , "Redesign.Store.Action"
            ]
        |> Simplify.rule
```

Overall I'm fine with the status quo. If this was separated into its own rule / package, I'd _probably_ not use it though.

**Comment by jfmengels** [comment]
@Janiczek Do you think your annoyances would be fully solved by only targetting custom types from dependencies? For instance, this means that the following would be simplified
```elm
case maybe of
  Just _ -> 1
  Nothing -> 1
--> 1
```
but not the following
```elm
case maybe of
  Just _ -> 1
  Nothing -> 1
--> 1
```

If we go this route, the previous configuration would become deprecated and unnecessary, and I'd probably remove it. Unless some people would like to ignore it for some custom types from dependencies? :thinking:

**Comment by Janiczek** [comment]
> Do you think your annoyances would be fully solved by only targetting custom types from dependencies?
Yeah that would absolutely work for me!
