### ISSUE TITLE
Simplify `a - a` to `0`

### ISSUE THREAD

**Issue by miniBill** [jfmengels/elm-review-simplify#41]
**What the rule should do:**
Simplify `a-a` to `0`

**Example of things the rule would report:**

```elm
item.quality - item.quality
--> 0
```

**Example of things the rule would not report:**

```elm
item.quality - (.quality item)
```

**Comment by jfmengels** [comment]
> item.quality - (.quality item)

Why would you not want this be reported? Except for the fact that it can be hard to detect (which may actually not be all that complicated).

I also think that we could report the following
```elm
item.quality + (-item.quality)
--> 0
```


And maybe we could also simplify things like (more work though)

```elm
item.quality + 3 - item.quality + n
--> 3 + n
```

though I don't know if this would create for annoyances in how you want to write your code.

**Comment by miniBill** [comment]
It would be reported after the `.quality item -> item.quality` transformation I guess?

`a + (-a)` should be fine

`a + 3 - a + n` would be more work

While we're at it, does it make sense to simplify

a) `(a + 1) + 1`
b) `a + 1 + 1
?

**Comment by jfmengels** [comment]
I don't think we have the `.quality item -> item.quality` transformation :thinking: 

For a) and b), do you mean to transform them to `a + 2`? I would say no, because that can be related to how you want to write code.

The example I usually have in mind is something like:

```elm
Process.sleep (3 * 60 * 1000)
```
Abole it becomes easy to see how long to wait: 1000 milliseconds is one second, times 60 is one minute, times 3 is 3 minutes.
We could simplify it to
```elm
Process.sleep 180000
```
but that would be a lot harder to read and feel like a much more arbitrary/magic value compared to the broken-down version we had before.

**Comment by miniBill** [comment]
Agreed!

**Comment by lue-bird** [comment]
@ future implementor: As with #58, these simplifications aren't always correct with `Float`
```elm
> (0 / 0) - (0 / 0)
NaN : Float
> (1 / 0) - (1 / 0)
NaN : Float
> -(1 / 0) - -(1 / 0)
NaN : Float
```

**Comment by miniBill** [comment]
I'm closing this in favor of creating https://github.com/miniBill/elm-review-optimize

**Comment by jfmengels** [comment]
I'll re-open this one, because I can still see this one being valuable in Simplify :)

**Comment by miniBill** [comment]
Considering what Lue said, I'm guessing that Simplify would have the rule but not the simplification, whereas Optimize could have both?

**Comment by jfmengels** [comment]
I don't know if I've written about it somewhere, but I think we'll introduce a configuration option to avoid/enable simplifications on potential `NaN`. Basically, if the user says "I never willingly work with NaN", then we enable the errors + fixes for things like `a - a --> 0` or `a == a --> True`. If they say the opposite, then we don't.

I think if you enable these changes anyway, then you're (more) at a risk of changing behavior with `Optimize`.

**Comment by miniBill** [comment]
I like it!
