### ISSUE TITLE
Spelling mistake in simplification summary of Maybe.andThen

### ISSUE THREAD

**Issue by lue-bird** [jfmengels/elm-review-simplify#73]
https://github.com/jfmengels/elm-review-simplify/blob/main/src/Simplify.elm#L350
should be
```elm
Maybe.andThen f Nothing
--> Nothing
```

**Comment by jfmengels** [comment]
Ahaa. I think that's where the `.and` in 28a70036f6b032da2fabfdab0e8932682d46ba69 comes from :sweat_smile:
